version: '2'

services:
        gitbucket:
                build: ./gitbucket
                restart: always
                container_name: gitbucket
                ports:
                 - 8084:8080
                volumes:
                 - /opt/gitbucket/.gitbucket:/root/.gitbucket
        postgres:
                build: ./postgres
                restart: always
                container_name: postgres
                environment:
                        POSTGRES_USER: gitbucket
                        POSTGRES_PASSWORD: gitbucket
        backup:
                build: ./backup
                restart: always
                container_name: backup
                volumes:
                 - /opt/gitbucket/backup:/root/backup

